### ISSUE TITLE
Design advice

### ISSUE THREAD

**Issue by paulalago** [FaraazJafri/COEN6311AA_Group8_Concordia-Travel-Web-Application#8]
Dear team,
I am leaving this comment here as I was quickly checking your code and found that you are directly creating a connection from your servlet to the database. 
This is not a good idea as you are combining the presentation layer with the data access layer. Servlet acts as a controller for the presentation layer whereas database connection should be done in the data access layer 
You could follow the Data Access Object Pattern https://www.oracle.com/java/technologies/data-access-object.html
A typical organization of the code would be :
Presentation Layer
  -> Views
  -> ViewModels  
  -> Controllers 

Service Layer
  -> Includes business logic
  -> Uses data access interfaces

Data Access Layer (DAOs)
  -> Contracts (interfaces) for persistent storage
  -> Interface implementations

Entities (or Models)
  -> POCO/ POJO that represent data

A request goes to the servlet which would call the service which would finally call the DAO. The model is used to send the information between layers. 

It is the DAO that would connect to the database and update it or read from it. Please try to refactor your code as soon as possible and organize it in folders following the components. 

In addition, try to use ConnectionPool instead of connection as opening a connection for each new request can have significant performance issues. You can read here https://docs.oracle.com/cd/E11882_01/java.112/e12265/connect.htm#CHDGEJJF

**Comment by FaraazJafri** [comment]
We have addressed the issue and properly segregated our dataaccess layer.
Closing the issue.
